### ISSUE TITLE
newbie question : how to use it ?

### ISSUE THREAD

**Issue by bobman38** [timonweb/django-bulma#1]
Yeah full newbie question sorry....

got the project in my django installed apps but....

I can write some docs and PR it if needed,

thanks !

**Comment by timonweb** [comment]
Hi, 

since the project is in the working phase, I didn't think anyone except me gonna use it and was going to write some instructions in the future, when it's ready and polished. However, some initial docs would be nice. 

If you want to help, I'm always glad to PR's. Just let me know if I should wait for your PR or do some docs myself.

Cheers!

**Comment by timonweb** [comment]
Merged, thank you!
